[supabase]
dialect = "postgresql"
host = "db.vhnzugddsmrutnagawhi.supabase.co"  # Пример: asdfghjklmn.supabase.co
database = "postgres"
username = "postgres"
password = "Fuckyou1988!"        # Пароль, который вы установили для базы данных
port = 5432
