# .streamlit/secrets.toml
[connections.supabase]
database_type = "postgresql"
host = "db.vhnzugddsmrutnagawhi.supabase.co"
port = 5432
username = "postgres"
password = "Fuckyou1988!"
database = "postgres"
